server:
  port: 6060
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/yueting?allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 5
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
#项目目录
project:
  folder: C:/webser/

#日志级别
log:
  root:
    level: debug
